# Generated by Django 3.2.9 on 2022-11-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='watchList',
            new_name='watchlist',
        ),
    ]
